name: Run the main job

on:
  # run the action every 1/2 hour
  schedule:
    - cron: "*/30 * * * *"
  # allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v4

      # install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # print some debug info to make sure things are working
      - name: Print debug info
        run: |
          pwd
          ls -al
          whoami
          date
          npm --version
          node --version

      # install JS dependencies
      - name: Install dependencies
        run: npm ci

      # download the artifacts from last run
      - run: |
          gh run download -n Results || true
          [ ! -f results.json ] || mv results.json previous-results.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # run the main script
      - name: Run main script
        env:
          SECRET_GMAIL_APP_PASSWORD: ${{ secrets.SECRET_GMAIL_APP_PASSWORD }}
          SECRET_QUOYLES_QUARTERS_DISCORD_WEBHOOK: ${{ secrets.SECRET_QUOYLES_QUARTERS_DISCORD_WEBHOOK }}
          SECRET_EAST_BAY_MAGIC_DISCORD_WEBHOOK: ${{ secrets.SECRET_EAST_BAY_MAGIC_DISCORD_WEBHOOK }}
        run: npm run main

      # upload the new results
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: results.json

