name: Run script

on:
  # run the action every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3

      # insstall Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # print some debug info to make sure things are working
      - name: Print debug info
        run: |
          pwd
          ls -al
          whoami
          date
          npm --version
          node --version

      # install js dependencies
      - name: Install dependencies
        run: npm ci

      # download the artifacts from last run
      - run: gh run download -n Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # make sure last run artifact was downloaded
      - name: Delete me
        run: |
          ls -al
          cat results.txt

      # run the main script
      - name: Run main script
        run: |
          npm run main

      # upload the new results
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: results.txt

