name: Run script

on:
  # run the action every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Print debug info
        run: |
          pwd
          ls -al
          whoami
          date
          npm --version
          node --version

      - name: Install dependencies
        run: npm ci

      - name: Run main script
        run: |
          echo 'test'
          echo 'console.log("test")' | node
